# Start Alacritty Themes
general.import = ["themes/colibri.toml"]
# End Alacritty Themes


[bell]
animation = "EaseOutExpo"
duration = 100

[font]
size = 10.0
normal= { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
italic = { family = "JetBrains Mono", style = "Italic" }

[window]
dimensions = { columns = 100, lines = 50 }
decorations = "None"
opacity = 0.98
