# Start Alacritty Themes
general.import = ["themes/colibri.toml"]
# End Alacritty Themes

[bell]
animation = "EaseOutExpo"
duration = 100

[font]
size = 12
# normal= { family = "Atkinson Hyperlegible Mono", style = "Regular" }
# bold = { family = "Atkinson Hyperlegible Mono", style = "Bold" }
# bold_italic = { family = "Atkinson Hyperlegible Mono", style = "Bold Italic" }
# italic = { family = "Atkinson Hyperlegible Mono", style = "Italic" }

[window]
dimensions = { columns = 100, lines = 50 }
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
  { key = "Enter", mods = "Control|Shift", action = "ToggleFullscreen"},
  { key = "Enter", mods = "Alt", action = "ToggleMaximized"},
]
